DROP TABLE IF EXISTS users;

CREATE TABLE IF NOT EXISTS users (id SERIAL PRIMARY KEY, last_name VARCHAR(50) NOT NULL, first_name VARCHAR(50) NOT NULL, email VARCHAR(50) NOT NULL UNIQUE, pass VARCHAR(50) NOT NULL UNIQUE);

DROP TABLE IF EXISTS schedules;

CREATE TABLE IF NOT EXISTS schedules (id SERIAL PRIMARY KEY, id_user VARCHAR(50) NOT NULL, day NUMERIC(1) NOT NULL, start_time TIMESTAMPTZ NOT NULL, end_time TIMESTAMPTZ NOT NULL);